version: "3.3"

services:
  dspacedb:
    image: dspace/dspace-postgres-pgcrypto
    container_name: dspacedb
    environment:
      - PGDATA=/pgdata
    ports:
      - 5432:5432
    volumes:
       - pgdataD6:/pgdata
    networks:
      - dspacenet
    tty: true
    stdin_open: true

  dspacetomcat:
    image: dspace/dspace-tomcat
    container_name: dspacetomcat
    environment:
      - DSPACE_INSTALL=/dspace
    ports:
      - 8080:8080
    volumes:
       - dspaceD6:/dspace
    networks:
       - dspacenet
    depends_on:
      - dspacedb
    tty: true
    stdin_open: true

volumes:
  pgdataD6:
  dspaceD6:

networks:
  dspacenet:
