version: "3.3"

services:
  dspacedb:
    image: dspace/dspace-postgres-pgcrypto
    # Note that a separate image exists for DSpace 4x
    # image: dspace/dspace-postgres-4x
    environment:
      - PGDATA=/pgdata
    volumes:
      - pgdata:/pgdata
    networks:
      - dspacenet
    tty: true
    stdin_open: true

  fuseki:
    image: "stain/jena-fuseki"
    ports:
      - 3030:3030
    environment:
      - ADMIN_PASSWORD=dspace
    networks:
      - dspacenet

  dspace:
    image: "dspace/dspace:${DSPACE_VER:-dspace-6_x}"
    environment:
      - DSPACE_INSTALL=/dspace
    ports:
      - 8080:8080
    volumes:
      - "assetstore:/dspace/assetstore"
      - "solr:/dspace/solr"
      # DSpace 6+: Uncomment the following to connect to fuseki
      - "./local.cfg:/dspace/config/local.cfg"
      # DSpace 5: Uncomment the following to connect to fuseki
      # - "./rdf.cfg_5x:/dspace/config/modules/rdf.cfg"
      # Uncomment the following to enable Mirage2 (DSpace 5x or 6x only)
      # - "../../add-ons/mirage2/xmlui.xconf:/dspace/config/xmlui.xconf"
      # Uncomment the following to enable non https access to the rest servcie
      # - "../../add-ons/rest_http/web5.xml:/dspace/webapps/rest/WEB-INF/web.xml"
      # - "../../add-ons/rest_http/web6.xml:/dspace/webapps/rest/WEB-INF/web.xml"
      # - "../../add-ons/rest_http/web7.xml:/dspace/webapps/rest/WEB-INF/web.xml"
      # Uncomment the following to enable non localhost access to the solr service
      # - "../../add-ons/solr_localhost/web5.xml:/dspace/webapps/solr/WEB-INF/web.xml"
      # - "../../add-ons/solr_localhost/web6.xml:/dspace/webapps/solr/WEB-INF/web.xml"
      # - "../../add-ons/solr_localhost/web7.xml:/dspace/webapps/solr/WEB-INF/web.xml"
    networks:
      - dspacenet
    depends_on:
      - dspacedb
    tty: true
    stdin_open: true

volumes:
  pgdata:
  assetstore:
  solr:
  fuseki:

networks:
  dspacenet:
