version: "3.3"

services:
  dspacedb:
    image: dspace/dspace-postgres-pgcrypto
    environment:
      - PGDATA=/pgdata
    volumes:
      - pgdata:/pgdata
    networks:
      - dspacenet
    tty: true
    stdin_open: true

  dspace:
    image: "dspace/dspace:${DSPACE_VER:-dspace-6_x-jdk8-test}"
    environment:
      - DSPACE_INSTALL=/dspace
    ports:
      - 8080:8080
    volumes:
      - "assetstore:/dspace/assetstore"
      - "solr:/dspace/solr"
      - "${DSPACE_SRC}:/dspace-src"
    networks:
      - dspacenet
    depends_on:
      - dspacedb
    tty: true
    stdin_open: true

volumes:
  pgdata:
  assetstore:
  solr:

networks:
  dspacenet:
