version: "3.3"

services:
  dspacedb:
    image: dspace/dspace-postgres-pgcrypto
    container_name: dspacedb
    # Note that a separate image exists for DSpace 4x
    # image: dspace/dspace-postgres-4x
    environment:
      - PGDATA=/pgdata
    volumes:
      - pgdata:/pgdata
    networks:
      - dspacenet
    tty: true
    stdin_open: true

  dspace:
    image: "${DOCKER_OWNER:-dspace}/dspace:${DSPACE_VER:-dspace-6_x-jdk8-test}"
    container_name: dspace
    environment:
      - DSPACE_INSTALL=/dspace
    ports:
      - 8080:8080
    volumes:
      - "assetstore:/dspace/assetstore"
      - "./local.cfg:/dspace/config/local.cfg"
      # Uncomment the following to enable Mirage2 (DSpace 5x or 6x only)
      # - "../../add-ons/mirage2/xmlui.xconf:/dspace/config/xmlui.xconf"
    networks:
      - dspacenet
    depends_on:
      - dspacedb
      - dspacesolr
    tty: true
    stdin_open: true

  dspacesolr:
    image: dspace/dspace-solr
    container_name: dspacesolr
    ports:
     - "8983:8983"
#    volumes:
#      - solrext:/opt/solr/server/solr/dspace-cores
    networks:
      - dspacenet
    tty: true
    stdin_open: true

volumes:
  pgdata:
  assetstore:
#  solrext:

networks:
  dspacenet:
