apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  containers:
  - image: dspace/dspace:dspace-6_x
    name: dspace
    #container_name: dspace
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    env:
    - name: db.url
      value: jdbc:postgresql://localhost:5432/dspace
  - image: dspace/dspace-postgres-pgcrypto
    name: dspacedb
    #container_name: dspacedb
    ports:
    - containerPort: 5432
      name: http
      protocol: TCP
