# kubectl apply -f dspace.deploy.v6.yaml
# kubectl get pods -o wide
# kubectl get services -o wide
# kubectl port-forward service/dspace-service 8080:8080
# kubectl apply -f dpace.job.create-admin.yaml
# kubectl delete -f dspace.deploy.v6.yaml
# https://stackoverflow.com/questions/57317501/kubernetes-modeling-jobs-cron-tasks-for-postgres-tomcat-application
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: local-config-map
  namespace: default
data:
  # example of a simple property defined using --from-literal
  #example.property.1: hello
  #example.property.2: world
  # example of a complex property defined using --from-file
  local.cfg: |-
    dspace.dir = /dspace
    db.url = jdbc:postgresql://dspacedb-service:5432/dspace
    dspace.hostname = dspace-service
    dspace.baseUrl = http://dspace-service:8080
    solr.server=http://dspace-service:8080/solr
---
apiVersion: v1
kind: Service
metadata:
  name: dspacedb-service
  labels:
    app: dspacedb-app
spec:
  type: NodePort
  selector:
    app: dspacedb-app
  ports:
  - protocol: TCP
    port: 5432
  #  targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dspacedb-deploy
  labels:
    app: dspacedb-app
spec:
  selector:
    matchLabels:
      app: dspacedb-app
  template:
    metadata:
      labels:
        app: dspacedb-app
    spec:
      volumes:
      - name: "pgdata-vol"
        # There is an outstanding bug that prevents PGDATA from being persisted on Windows.
        # On MacOS or other platforms, a hostPath could be used.
        #emptyDir: {}
        hostPath:
          path: "/tmp/vols/pgdata"
      containers:
      - image: dspace/dspace-postgres-pgcrypto
        name: dspacedb
        ports:
        - containerPort: 5432
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: "/pgdata"
          name: "pgdata-vol"
        env:
        - name: PGDATA
          value: /pgdata
        readinessProbe:
          exec:
            command: ["psql", "-U", "dspace", "-c", "SELECT 1"]
          initialDelaySeconds: 10
          timeoutSeconds: 2
        livenessProbe:
          exec:
            command: ["psql", "-U", "dspace", "-c", "SELECT 1"]
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: dspace-service
  labels:
    app: dspace-app
spec:
  type: NodePort
  selector:
    app: dspace-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dspace-deploy
  labels:
    app: dspace-app
spec:
  selector:
    matchLabels:
      app: dspace-app
  template:
    metadata:
      labels:
        app: dspace-app
    spec:
      volumes:
      - name: "assetstore"
        hostPath:
          path: "/tmp/vols/assetstore"
      - name: my-local-config-map
        configMap:
          name: local-config-map
      - name: "solr-authority"
        hostPath:
          path: "/tmp/vols/solr-authority"
      - name: "solr-oai"
        hostPath:
          path: "/tmp/vols/solr-oai"
      - name: "solr-search"
        hostPath:
          path: "/tmp/vols/solr-search"
      - name: "solr-statistics"
        hostPath:
          path: "/tmp/vols/solr-statistics"
      containers:
      - image: dspace/dspace:dspace-6_x-jdk8-test
        name: dspace
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: "/dspace/assetstore"
          name: "assetstore"
        - mountPath: "/dspace/config/local.cfg"
          name: "my-local-config-map"
          subPath: local.cfg
        - name: "solr-authority"
          mountPath: "/opt/solr/server/solr/authority/data"
        - name: "solr-oai"
          mountPath: "/opt/solr/server/solr/oai/data"
        - name: "solr-search"
          mountPath: "/opt/solr/server/solr/search/data"
        - name: "solr-statistics"
          mountPath: "/opt/solr/server/solr/statistics/data"
        readinessProbe:
          httpGet:
            path: /xmlui/contact
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30
        livenessProbe:
          httpGet:
            path: /xmlui/contact
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 5
          periodSeconds: 120
