apiVersion: v1
kind: Pod
metadata:
  name: dspace-pod
spec:
  volumes:
  - name: "assetstore"
    hostPath:
      path: "/c/temp/vols/assetstore"
  - name: "local-cfg"
    hostPath:
      path: "/c/users/twb27/Documents/GitHub/DSpace-Docker-Images/kubernetes/k8.cfg"
  containers:
  - image: dspace/dspace:dspace-6_x
    name: dspace
    #container_name: dspace
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    env:
    - name: db.url
      value: jdbc:postgresql://localhost:5432/dspace
    volumeMounts:
    - mountPath: "/dspace/assetstore"
      name: "assetstore"
    - mountPath: "/dspace/config/local.cfg"
      name: "local-cfg"
    #resources:
    #  requests:
    #    cpu: "1000m"
    #    memory: "4Gi"
  - image: dspace/dspace-postgres-pgcrypto
    name: dspacedb
    #container_name: dspacedb
    ports:
    - containerPort: 5432
      name: http
      protocol: TCP
    #resources:
    #  requests:
    #    cpu: "500m"
    #    memory: "1Gi"
