apiVersion: v1
kind: Pod
metadata:
  name: dspace-pod
spec:
  volumes:
  - name: "pgdata-vol"
  # The postgres PGDATA volume cannot be persisted on Windows.  On Windows, use emptyDir.
  # See https://stackoverflow.com/questions/57227990/kubernetes-in-docker-for-windows-volume-configuration-for-postgres
    emptyDir: {}
  #  The following hostPath configuration
  #  hostPath:
  #    path: /tmp/vols/pgdata
  #
  - name: "assetstore"
  # This volume behaves properly on on Windows, but it does not make sense to persist the assetstore
  # if the database cannot be persisted.
    emptyDir: {}
  #  hostPath:
  #    path: "/tmp/vols/assetstore"
  #
  - name: my-local-config-map
    configMap:
      name: local-config-map
  containers:
  - image: dspace/dspace:dspace-6_x
    name: dspace
    #container_name: dspace
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    volumeMounts:
    - mountPath: "/dspace/assetstore"
      name: "assetstore"
    - mountPath: "/dspace/config/local.cfg"
      name: "my-local-config-map"
      subPath: local.cfg
  #
  - image: dspace/dspace-postgres-pgcrypto
    name: dspacedb
    #container_name: dspacedb
    ports:
    - containerPort: 5432
      name: http
      protocol: TCP
    volumeMounts:
    - mountPath: "/pgdata"
      name: "pgdata-vol"
    env:
    - name: PGDATA
      value: /pgdata
