apiVersion: v1
kind: Pod
metadata:
  name: dspace-pod
spec:
  volumes:
  - name: "assetstore"
    hostPath:
      path: "/c/temp/vols/assetstore"
  #- name: "pgdata-vol"
  #  emptyDir: {}
  #  hostPath:
  #    path: "/c/temp/vols/pgdata"
  #    type: DirectoryOrCreate
  - name: "pgdata-vol"
    type: PersistentVolume
    local:
      path: "/c/temp/vols/pgdata"
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - node1
  - name: "local-cfg"
    hostPath:
      path: "/c/users/twb27/Documents/GitHub/DSpace-Docker-Images/kubernetes/k8.cfg"
  containers:
  - image: dspace/dspace:dspace-6_x
    name: dspace
    #container_name: dspace
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    volumeMounts:
    - mountPath: "/dspace/assetstore"
      name: "assetstore"
    - mountPath: "/dspace/config"
      name: "local-cfg"
    #resources:
    #  requests:
    #    cpu: "1000m"
    #    memory: "4Gi"
  - image: dspace/dspace-postgres-pgcrypto
    name: dspacedb
    #container_name: dspacedb
    ports:
    - containerPort: 5432
      name: http
      protocol: TCP
    volumeMounts:
    - mountPath: "/pgdata"
      name: "pgdata-vol"
    env:
    - name: PGDATA
      value: /pgdata
    #resources:
    #  requests:
    #    cpu: "500m"
    #    memory: "1Gi"
