version: "3.7"

services:
  dspacedb:
    image: dspace/dspace-postgres-4x

  dspace:
    image: "${DOCKER_OWNER:-dspace}/dspace:${DSPACE_VER:-dspace-4_x-jdk7-test}"
    volumes:
      - "solr_authority:/dspace/solr/authority/data"
      - "solr_oai:/dspace/solr/oai/data"
      - "solr_search:/dspace/solr/search/data"
      - "solr_statistics:/dspace/solr/statistics/data"
    environment:
      - SCRIPTVER=4
