networks:
  dspacenet: {}
services:
  dspace:
    container_name: dspace
    depends_on:
    - dspacedb
    entrypoint: /dspace-docker-tools/ingestAIP.sh
    environment:
      ADMIN_EMAIL: test@test.edu
      ADMIN_FNAME: AdminFirst
      ADMIN_LNAME: AdminLast
      ADMIN_PASS: admin
      AIPWAIT: '5'
      AIPZIP: https://github.com/DSpace-Labs/AIP-Files/raw/master/dogAndReport.zip
      DBWAIT: '20'
      DSPACE_INSTALL: /dspace
      LOADASSETS: https://www.dropbox.com/s/zv7lj8j2lp3egjs/assetstore.tar.gz?dl=1
      SCRIPTVER: '7'
      SKIPAIP: "Y"
      db__P__url: jdbc:postgresql://dspacedb:5432/dspace
      dspace__P__baseUrl: http://localhost:8080
      dspace__P__dir: /dspace
      dspace__P__hostname: localhost
      dspace__P__name: DSpace Started with Docker Compose
    image: dspace/dspace:dspace-7_x-jdk8-test
    networks:
      dspacenet: {}
    ports:
    - published: 8080
      target: 8080
    stdin_open: true
    tty: true
    volumes:
    - "../../add-ons/dspace-docker-tools:/dspace-docker-tools"
    - assetstore:/dspace/assetstore
  dspacedb:
    container_name: dspacedb
    environment:
      LOADSQL: https://www.dropbox.com/s/xh3ack0vg0922p2/configurable-entities-2019-05-08.sql?dl=1
      PGDATA: /pgdata
    image: dspace/dspace-postgres-pgcrypto:loadsql
    networks:
      dspacenet: {}
    stdin_open: true
    tty: true
    volumes:
    - "../../add-ons/dspace-docker-tools:/dspace-docker-tools"
    - pgdata:/pgdata
  dspacesolr:
    container_name: dspacesolr
    image: dspace/dspace-solr
    networks:
      dspacenet: {}
    ports:
    - published: 8983
      target: 8983
    stdin_open: true
    tty: true
    volumes:
    - solr_authority:/opt/solr/server/solr/authority/data
    - solr_oai:/opt/solr/server/solr/oai/data
    - solr_search:/opt/solr/server/solr/search/data
    - solr_statistics:/opt/solr/server/solr/statistics/data
version: '3.7'
volumes:
  assetstore: {}
  pgdata: {}
  solr_authority: {}
  solr_oai: {}
  solr_search: {}
  solr_statistics: {}
