# suitable for DSpace 6 and 7
version: "3.7"

services:
  dspace:
    environment:
     # Double underbars in env names will be replaced with periods for apache commons
     - rdf__contextPath=http://localhost:8080/rdf
     - rdf__storage__graphstore__endpoint=http://fuseki:3030/dspace/data
     - rdf__public__sparql__endpoint=http://fuseki:3030/dspace/sparql
     - rdf__storage__graphstore__authentication=yes
     - rdf__storage__graphstore__login=admin
     - rdf__storage__graphstore__password=dspace
     - rdf__storage__sparql__authentication=yes
     - rdf__storage__sparql__login=admin
     - rdf__storage__sparql__password=dspace
  fuseki:
    image: "stain/jena-fuseki"
    container_name: fuseki
    ports:
      - 3030:3030
    environment:
      - ADMIN_PASSWORD=dspace
    networks:
      - dspacenet
