# suitable for DSpace 6 and 7
version: "3.7"

services:
  dspace:
    environment:
      - LOCALCFG3=
        \n# LOCALCFG3 overrides
        \nrdf.contextPath = http://localhost:8080/rdf
        \nrdf.storage.graphstore.endpoint = http://fuseki:3030/dspace/data
        \nrdf.public.sparql.endpoint = http://fuseki:3030/dspace/sparql
        \nrdf.storage.graphstore.authentication = yes
        \nrdf.storage.graphstore.login = admin
        \nrdf.storage.graphstore.password = dspace
        \nrdf.storage.sparql.authentication = yes
        \nrdf.storage.sparql.login = admin
        \nrdf.storage.sparql.password = dspace
  fuseki:
    image: "stain/jena-fuseki"
    container_name: fuseki
    ports:
      - 3030:3030
    environment:
      - ADMIN_PASSWORD=dspace
    networks:
      - dspacenet
