# suitable for DSpace 6 and 7
version: "3.7"

services:
  dspace:
    environment:
      - JAVA_OPTS=
        -Drdf.contextPath=http://localhost:8080/rdf
        -Drdf.storage.graphstore.endpoint=http://fuseki:3030/dspace/data
        -Drdf.public.sparql.endpoint=http://fuseki:3030/dspace/sparql
        -Drdf.storage.graphstore.authentication=yes
        -Drdf.storage.graphstore.login=admin
        -Drdf.storage.graphstore.password=dspace
        -Drdf.storage.sparql.authentication=yes
        -Drdf.storage.sparql.login=admin
        -Drdf.storage.sparql.password=dspace
  fuseki:
    image: "stain/jena-fuseki"
    container_name: fuseki
    ports:
      - 3030:3030
    environment:
      - ADMIN_PASSWORD=dspace
    networks:
      - dspacenet
