# suitable for DSpace 6 and 7
version: "3.7"

services:
  dspace:
    environment:
      # __D__ -> -
      # __P__ -> .
      - sword__D__server__P__enabled=true
      - sword__D__server__P__path=sword
      - sword__D__server__P__url=${BASEROOT:-http://localhost:8080}/sword
      - sword__D__server__P__collection__P__url=${BASEROOT:-http://localhost:8080}/sword/collection
      - sword__D__server__P__servicedocument__P__url=${BASEROOT:-http://localhost:8080}/sword/servicedocument
      #
      - swordv2__D__server__P__enabled=true
      - swordv2__D__server__P__path=swordv2
      - swordv2__D__server__P__url=${BASEROOT:-http://localhost:8080}/swordv2
      - swordv2__D__server__P__collection__P__url=${BASEROOT:-http://localhost:8080}/swordv2/collection
      - swordv2__D__server__P__servicedocument__P__url=${BASEROOT:-http://localhost:8080}/swordv2/servicedocument
