version: "3.3"

services:
  dspacedb:
    image: dspace/dspace-postgres-pgcrypto
    environment:
      - PGDATA=/pgdata
    volumes:
      - pgdata:/pgdata
    networks:
      - dspacenet
    tty: true
    stdin_open: true

  dspace:
    #image: "dspace/dspace:${DSPACE_VER:-master}"
    image: dspace/dspace:master
    environment:
      - DSPACE_INSTALL=/dspace
    ports:
      - 8080:8080
    volumes:
      - "dspace:/dspace"
    networks:
      - dspacenet
    depends_on:
      - dspacedb
    tty: true
    stdin_open: true

  dspace-angular:
    image: dspace/dspace-angular
    ports:
      - 3000:3000
      - 9876:9876
    environment:
      - DSPACE_SSL=false
      - DSPACE_HOST=dspace-angular
      - DSPACE_PORT=3000
      - DSPACE_REST_HOST=dspace
      - DSPACE_REST_SSL=false
      - DSPACE_REST_NAMESPACE=/spring-rest/
      - DSPACE_REST_PORT=8080
    networks:
      - dspacenet
    depends_on:
      - dspace
    tty: true
    stdin_open: true

volumes:
  pgdata:
  dspace:

networks:
  dspacenet:
