version: "3.3"

services:
  dspacedb:
    image: dspace/dspace-postgres-pgcrypto
    environment:
      - PGDATA=/pgdata
    volumes:
      - pgdata:/pgdata
    networks:
      - dspacenet
    tty: true
    stdin_open: true

  dspace:
    image: "dspace/dspace:${DSPACE_VER:-master}"
    environment:
      - DSPACE_INSTALL=/dspace
    ports:
      - 8080:8080
    volumes:
      - "dspace:/dspace"
    networks:
      - dspacenet
    depends_on:
      - dspacedb
    tty: true
    stdin_open: true

  dspace-angular:
    image: dspace/dspace-angular
    environment:
      #- DSPACE7-SPRING-REST=https://dspace7.4science.it/dspace-spring-rest/
      - DSPACE7-SPRING-REST=http://dspace/dspace-spring-rest/
    ports:
      - 3000:3000
    networks:
      - dspacenet
    depends_on:
      - dspace
    tty: true
    stdin_open: true


volumes:
  pgdata:
  dspace:

networks:
  dspacenet:
