version: "3.7"

services:
  dspace-cli:
    volumes:
    - "./ingest.sh:/tmp/ingest.sh"
    environment:
    - AIPZIP=https://github.com/DSpace-Labs/AIP-Files/raw/master/dogAndReport.zip
    - ADMIN_EMAIL=test@test.edu
    - AIPDIR=/tmp/aip-dir
    entrypoint: /bin/bash /tmp/ingest.sh
